### ISSUE TITLE
List of services to add

### ISSUE THREAD

**Issue by amureki** [amureki/statuscheck#1]
## Todo
We need to implement the most important/popular (for the community) services. Also, those ones are important to us:

- [ ] AWS https://status.aws.amazon.com/
- [ ] NPM https://status.npmjs.org/
- [ ] Telegram (no API or public status pages)
- [ ] Discord https://status.discordapp.com/
- [ ] CloudAMQP http://status.cloudamqp.com/
- [ ] Redislabs https://status.redislabs.com/
- [ ] Close.io https://status.close.io/

## Howto
1. Add service to the list of available services:
https://github.com/amureki/statuscheck/blob/master/statuscheck/services/__init__.py
2. Provide service module. Some examples are here:
https://github.com/amureki/statuscheck/tree/master/statuscheck/services (note, that if status page is operated by https://www.statuspage.io/, there is a special base class for that.

**Comment by IvanDelsinne** [comment]
Those are my propositions

- [ ] Signal messenger
- [ ] OVH
- [ ] PHPNet
- [ ] SparkPost

**Comment by ghost** [comment]
Hi, thanks for your great work, here are some suggestions, if it is OK?

**Paddle** (Payment processing service, like Stripe):
class ServiceAPI(BaseStatusIOAPI):
    name = "Paddle"
    domain_id = "58b845a59243e72262001ccf"
    status_url = "https://paddle.status.io/"
    service_url = "https://paddle.io"

**Intercom** (CRM and Support service):
class ServiceAPI(BaseStatusPageAPI):
    name = "Intercom"
    domain_id = "1m1j8k4rtldg"
    status_url = "https://status.intercom.io/"
    service_url = "https://intercom.io"

**Notion** (Workspaces for teams):
class ServiceAPI(BaseStatusPageAPI):
    name = "Notion"
    domain_id = "kgl53swp0yg1"
    status_url = "https://status.notion.so"
    service_url = "https://notion.so"

**Figma** (Colaborative Design and Protoyping service):
class ServiceAPI(BaseStatusPageAPI):
    name = "Figma"
    domain_id = "rxpksf93ynw6"
    status_url = "https://status.figma.com/"
    service_url = "https://figma.com/"

**Comment by amureki** [comment]
Hey @Chris-Kaye !

Thank you for your proposal!
I definitely won't be against adding more things to the list! However, I am a bit overwhelmed with other things right now, so cannot promise you that I will be able to do it soon.

If you are feeling comfortable, surely shoot me with a PR addressing your services. I'd definitely review and release it then!

Best,
Rust

**Comment by owocado** [comment]
interesting, is this abandoned now?

**Comment by amureki** [comment]
> interesting, is this abandoned now?

I am not developing and maintaining this package, as it seems like there is no demand for it.

@owocado do you mind me asking, what brought your attention here? Were you in need of some tooling?

Best,
Rust

**Comment by owocado** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/24418520?u=4ef17f8d8e362b9049936c50d69f402349dc2ead&amp;v=4&amp;size=80">@owocado](https://github.com/owocado?rgh-link-date=2025-02-03T09%3A34%3A06.000Z) do you mind me asking, what brought your attention here? Were you in need of some tooling?

Heyyy, what brought me here was me searching for list of companies using Atlassian Statuspage because I ended up making similar feed but for Discord chat app. Currently I have 70 such feeds configured and it works well. 😇 

![Image](https://github.com/user-attachments/assets/8373aa7b-55e4-4cb7-9014-6566eb6a0d3d)

**Comment by amureki** [comment]
> > [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/24418520?u=4ef17f8d8e362b9049936c50d69f402349dc2ead&amp;v=4&amp;size=80">@owocado](https://github.com/owocado?rgh-link-date=2025-02-03T09%3A34%3A06.000Z) do you mind me asking, what brought your attention here? Were you in need of some tooling?
> 
> Heyyy, what brought me here was me searching for list of companies using Atlassian Statuspage because I ended up making similar feed but for Discord chat app. Currently I have 70 such feeds configured and it works well. 😇
> 
> ![Image](https://github.com/user-attachments/assets/8373aa7b-55e4-4cb7-9014-6566eb6a0d3d)

That's lovely :)
Wish you a good progress and traction on this project!

I had my biggest struggles with AWS status page (and a couple of services that have a massive number of servers in different regions) - that was upsetting me a lot.
